version: 2

updates:
  # Enable updates to the dependencies of our workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  # Enable updates to the dependencies of our Dockerfile
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '05:00'
